Dev/d meson
Harvard-Neutrino/LeptonInjector pull request #74
Opened 2024-08-22 19:18 UTC by MiaochenJin

2024-08-22 20:40 UTC, nickkamp1 requested changes
looks good, just need to remove some debug printouts and a few files that are used for analysis of d meson events. I will merge after testing this locally, but @austinschneider feel free to take a look and leave comments if you would like

2024-08-22 20:40 UTC, nickkamp1 commented on projects/dataclasses/public/SIREN/dataclasses/ParticleTypes.def
@nickkamp1 be sure to update this when you merge your HNL branch

2024-08-22 20:40 UTC, nickkamp1 commented on projects/distributions/private/secondary/vertex/SecondaryBoundedVertexDistribution.cxx
remove debug statements

2024-08-22 20:40 UTC, nickkamp1 commented on projects/injection/private/Injector.cxx
remove debug lines in the catch statement for the secondary process sampling, i.e. the "//////" lines

2024-08-22 20:40 UTC, nickkamp1 commented on projects/injection/private/Weighter.cxx
add a "Hadronization" target type and change the isQuark if statement to check the target type instead

2024-08-22 20:40 UTC, nickkamp1 commented on projects/interactions/private/CharmDISFromSpline.cxx
remove check_criteria logic

2024-08-22 20:40 UTC, nickkamp1 commented on projects/interactions/private/DMesonELoss.cxx
remove unnecessary include statements (splinetable)

2024-08-22 20:40 UTC, nickkamp1 commented on projects/interactions/private/pybindings/CharmMesonDecay.h
optional: include pybindings for total/differential decay width

2024-08-22 20:40 UTC, nickkamp1 commented on projects/utilities/public/SIREN/utilities/Constants.h
@nickkamp1 update with the HNL PR

2024-08-22 20:40 UTC, nickkamp1 commented on python/SIREN_Controller.py
@nickkamp1 verify that SaveWeighter works

2024-08-22 20:40 UTC, nickkamp1 commented on resources/Examples/DMesonExample/make_plots.py
leave this in the dev version of the branch for now. we will add in once we write a paper on the D meson signatures in SIREN and turn this into a notebook reproducing paper plots

2024-08-22 20:40 UTC, nickkamp1 commented on resources/Examples/DMesonExample/paper.mplstyle
move this to dev branch only too

2024-08-22 20:40 UTC, nickkamp1 commented on resources/Examples/DMesonExample/parse_output.py
move this to dev too

2024-08-22 21:04 UTC, MiaochenJin commented on projects/interactions/private/DMesonELoss.cxx
removed!

2024-08-22 21:04 UTC, MiaochenJin commented on projects/injection/private/Weighter.cxx
changed and verified that it works

2024-08-22 21:11 UTC, MiaochenJin commented on projects/interactions/private/pybindings/CharmMesonDecay.h
Will do after full implementation of fragmentation

2024-08-22 21:36 UTC, MiaochenJin commented on projects/distributions/private/secondary/vertex/SecondaryBoundedVertexDistribution.cxx
resolved

2024-08-22 21:43 UTC, MiaochenJin commented on projects/injection/private/Injector.cxx
resolved

2024-08-22 21:43 UTC, MiaochenJin commented on projects/interactions/private/CharmDISFromSpline.cxx
resolved

2024-08-22 21:47 UTC, MiaochenJin commented on resources/Examples/DMesonExample/make_plots.py
deleted

2024-08-22 21:47 UTC, MiaochenJin commented on resources/Examples/DMesonExample/parse_output.py
deleted

2024-08-22 21:48 UTC, MiaochenJin commented on resources/Examples/DMesonExample/paper.mplstyle
moved

2024-08-22 21:49 UTC, MiaochenJin commented
Made changes! made request of new round of review, please check if the changes are made

2024-08-23 16:03 UTC, austinschneider commented
I'm starting to take a look now. I'll provide detailed comments sometime today :)

2024-08-23 16:43 UTC, austinschneider commented
It is not clear to me that we need this `Hadronization` class or any of the specialized logic for hadronization that has been added to other classes.

In the way that it has been implemented here, can't the hadronization process just be implemented as a new decay process with `decay_length=0`?

2024-08-23 16:58 UTC, austinschneider commented
Regardless of if we keep the `Hadronization` class and the related pieces, it seems odd to me that the way these hadronization checks/cases are coded is such that it short circuits most of the existing logic. It seems that this has been written with the expectation that if an injection contains a hadronization process at all that the rest of the interactions should be ignored. Whatever solution we land on it should integrate with the rest of the interaction logic without short-circuiting things.

2024-08-23 17:18 UTC, austinschneider requested changes

2024-08-23 17:18 UTC, austinschneider commented on projects/detector/private/DetectorModel.cxx
> +    if(direction.magnitude() == 0 || direction.magnitude() <= 1e-5) {
```suggestion
    // Check that direction is approximately zero
    if(direction.magnitude() <= 1e-5) {
```

2024-08-23 17:18 UTC, austinschneider commented on projects/detector/private/DetectorModel.cxx
Was there a specific issue that the `distance.magnitude() <= 1e-5` checks fixed?

I'm wondering if there is another underlying issue that this is covering up, or if we really need this fix.

2024-08-23 17:18 UTC, austinschneider commented on projects/detector/private/DetectorModel.cxx
For the `direction.magnitude() <= 1e-5` checks, you should put the 1e-5 constant into the `projects/detector/public/SIREN/detector/DetectorModel.h` header

```c++
class DetectorModel {
public:
    constexpr static double distance_threshold = 1e-5;
```

and then use this constant to perform the checks in the `.cxx` file.

2024-08-23 17:18 UTC, austinschneider commented on projects/detector/private/DetectorModel.cxx
> +    }
```suggestion
    if(direction.magnitude() <= 1e-5) {
        return 0.0;
    }
```

2024-08-23 17:18 UTC, austinschneider commented on projects/distributions/private/secondary/vertex/SecondaryBoundedVertexDistribution.cxx
Instead of adding special login in this class checks for a hadronization interaction to change the class behavior, you should implement a new secondary vertex distribution that has the appropriate behavior for hadronization.

2024-08-23 17:18 UTC, austinschneider commented on projects/distributions/private/secondary/vertex/SecondaryPhysicalVertexDistribution.cxx
Same comment as for the bounded vertex distribution:

> Instead of adding special login in this class checks for a hadronization interaction to change the class behavior, you should implement a new secondary vertex distribution that has the appropriate behavior for hadronization.

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/private/Injector.cxx
It seems to me that the hadronization can be implemented as a decay process. Making that change would remove the need for most of the changes in this file.

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/private/Injector.cxx
It's been a while since I've thought about the "try/fail" logic in the injection, but I think will eventually want to add some logic for configuring these settings and keeping track of how many times this happens on each event. These changes to not necessarily need to be in this PR though.

I am curious as to why this logic was changed / why the number of tries was increased. Was there some issue that you were running into during injection that caused a failure? Does it still fail regularly? Was an increase in the number of tries needed for the injection to be successful?

2024-08-23 17:18 UTC, austinschneider commented on projects/interactions/public/SIREN/interactions/InteractionCollection.h
> +#include <cereal/types/base_class.hpp>
```suggestion
#include <cereal/types/base_class.hpp>
```

2024-08-23 17:18 UTC, austinschneider commented on projects/interactions/public/SIREN/interactions/InteractionCollection.h
> +
```suggestion
```

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/private/Injector.cxx
> +
```suggestion
```

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/public/SIREN/injection/ColumnDepthLeptonInjector.h
> +
```suggestion
```

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/public/SIREN/injection/CylinderVolumeLeptonInjector.h
> +
```suggestion
```

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/public/SIREN/injection/DecayRangeLeptonInjector.h
> +
```suggestion
```

2024-08-23 17:18 UTC, austinschneider commented on projects/injection/public/SIREN/injection/RangedLeptonInjector.h
> +
```suggestion
```

2026-05-03 03:44 UTC, MiaochenJin commented
## Summary                                                                                                                                                    
                                                            
  Adds charm-DIS injection support to SIREN — primary neutrino-on-nucleon DIS                                                                                   
  that emits D mesons directly as secondaries, plus the secondary D-meson
  decay and energy-loss machinery needed to track D mesons through to their                                                                                     
  final-state products. Used in IceCube high-energy charm analyses.                                                                                             
                                                                                                                                                                
  ## What this branch adds vs. `main`                                                                                                                           
                                                                                                                                                                
  ### New cross-section / interaction classes                                                                                                                   
   
  - **`QuarkDISFromSpline`** (`projects/interactions/{public,private}/...QuarkDISFromSpline.{h,cxx}`) —                                                         
    spline-based DIS cross section parameterised on charm-quark final states.
    Loads upstream FITS splines (`differential` + `total`), supports                                                                                            
    CC / NC / GR `interaction_type_`, and emits a `[lepton, hadrons, D-meson]`                                                                                  
    signature per primary × target × D-meson type. The D-meson set is selected                                                                                  
    per-primary by parity (ν → {D⁰, D⁺}, ν̄ → {D̄⁰, D⁻}), guaranteeing charm                                                                                      
    conservation in mixed-flavor instances.                                                                                                                     
                                                                                                                                                                
  - **`PythiaDISCrossSection`** — Pythia8/LHAPDF-driven DIS cross section,                                                                                      
    same physics coverage as `QuarkDISFromSpline` but with Pythia-based
    sampling. Drop-in alternative.                                                                                                                              
                                                                                                                                                                
  - **`CharmMesonDecay`** + **`CharmMesonDecay3Body`** — semileptonic D-meson                                                                                   
    decay (`D → K ℓ ν`) and 3-body decay variants. Hadronization-class                                                                                          
    classes (not Interaction); used as secondary collections.                                                                                                   
                                                                                                                                                                
  - **`DMesonELoss`** — D-meson energy-loss cross section, applies to D                                                                                         
    mesons propagating through detector material as secondaries.                                                                                                
                                                                                                                                                                
  ### New resources / examples                              

  - `resources/examples/example1/DIS_IceCube_charm.py` — end-to-end charm                                                                                       
    injection example using SIREN's current Injector/Weighter idiom (no
    `SIREN_Controller`, no `Add*Distribution(...)` API). Runs to 100+ events                                                                                    
    cleanly.                                                                                                                                                    
                                                                                                                                                                
  - `python/SIREN_Controller.py` — back-compat patch for upstream's                                                                                             
    `python_interface` refactor (PR #71): updates to use    
    `_util.load_detector(experiment)` and the new `.distributions` list                                                                                         
    property in place of the removed `Add*Distribution` setters.                                                                                                
                                                                                                                                                                
  ### New constants                                                                                                                                             
                                                                                                                                                                
  - `projects::utilities::Constants` — adds `D0Mass = 1.86484` (PDG D⁰),                                                                                        
    `DPlusMass = 1.86966` (PDG D⁺), and supporting decay-form-factor
    constants (`alpha`, `m_star_squared`, etc.).                                                                                                                
                                                                                                                                                                
  ### Build / dependency integration                                                                                                                            
                                                                                                                                                                
  - `projects/interactions/CMakeLists.txt` — Pythia8 + LHAPDF detection and                                                                                     
    link wiring, gated on user-provided `PYTHIA8_DIR` / `LHAPDF_DIR` cache
    variables (defaults configurable to a system install).                                                                                                      
                                                                                                                                                                
  - `cmake/photospline_patches/` + `cmake/Packages/photospline.cmake` —                                                                                         
    workaround for an upstream-pinned `photospline` revision that's missing                                                                                     
    `bsplvb_simple` / `bspline_deriv_nonzero` impls. Patches restore the 3                                                      [...]

2026-05-15 16:11 UTC, nickkamp1 requested changes
This looks pretty good to go, I left a handful of inline comments, and I think we still need to address some of @austinschneider's comments. The biggest comments I have are:

- let's remove extraneous comments everywhere they appear. I saw a lot in this PR
- how do we want to handle building the pythia libraries for the PythiaDISCrossSection class? I think the code now assumes SIREN is built against Pythia libraries, but that is using a hard-coded path to Andy's pythia installation. we need to treat this more carefully for the main branch

2026-05-15 16:11 UTC, nickkamp1 commented on .gitignore
I think we do not want to ignore vendor updates, no?

2026-05-15 16:11 UTC, nickkamp1 commented on projects/dataclasses/public/SIREN/dataclasses/ParticleTypes.def
> +X(CharmBar, -4)
can we not use the c and cBar particles defined above? also probably good to group K0/K0Bar with the other mesons

2026-05-15 16:11 UTC, nickkamp1 commented on projects/detector/private/DetectorModel.cxx
@MiaochenJin did we ever resolve this?

2026-05-15 16:11 UTC, nickkamp1 commented on projects/dataclasses/private/InteractionRecord.cxx
remove extraneous comments

2026-05-15 16:11 UTC, nickkamp1 commented on cmake/Packages/photospline.cmake
have you checked that this patch does not break the other splines used in SIREN? also what is the purpose of this patch?

2026-05-15 16:11 UTC, nickkamp1 commented on projects/distributions/private/secondary/vertex/SecondaryBoundedVertexDistribution.cxx
@MiaochenJin are we still using Secondary{Bounded,Physical}VertexDistribution for charms? I think it's probably ok as long as we add a check that any particle with hadronization interactions has no scattering or decay interactions present, since hadronization would override those

2026-05-15 16:11 UTC, nickkamp1 commented on projects/injection/private/Injector.cxx
I believe we started this way, but Andy found some issues with setting the decay length to zero (which is the physical behavior of hadronization). @MiaochenJin correct me if I'm wrong

2026-05-15 16:11 UTC, nickkamp1 commented on projects/distributions/private/secondary/vertex/SecondaryPhysicalVertexDistribution.cxx
> +    if (prob_density == 0) {
is this still necessary?

2026-05-15 16:11 UTC, nickkamp1 commented on projects/injection/private/Weighter.cxx
> +        // std::cout << "New Event" << std::endl;
remove extraneous comments

2026-05-15 16:11 UTC, nickkamp1 commented on projects/injection/private/Weighter.cxx
> +                    // if (phys_prob == 0) {
remove

2026-05-15 16:11 UTC, nickkamp1 commented on projects/injection/private/Weighter.cxx
> +
remove

2026-05-15 16:11 UTC, nickkamp1 commented on projects/injection/private/WeightingUtils.cxx
> +                    // if (total_xs == 0) {
remove

2026-05-15 16:11 UTC, nickkamp1 commented on projects/injection/private/WeightingUtils.cxx
> +                        double final_prob = cross_section->FinalStateProbability(record);
remove

2026-05-15 16:11 UTC, nickkamp1 commented on projects/interactions/private/PythiaDISCrossSection.cxx
I think we want to add an optional install of Pythia to the SIREN build system, similar to how we have Marley handled now

2026-05-15 16:15 UTC, nickkamp1 commented on projects/injection/public/SIREN/injection/Weighter.tcc
this logic probably needs to be checked against existing cross section classes... I don't think they all have TotalCrossSectionAllFinalStates. @MiaochenJin I thought we had agreed to update the way QuarkDISFromSpline handles TotalCrossSection(fake_record), no? i.e., it would check the final state and not double-count

2026-05-15 19:44 UTC, austinschneider commented on projects/interactions/private/PythiaDISCrossSection.cxx
Agreed. I don't think we can realistically ship binary python wheels that include a full Pythia installation.

Gating this in CMake (as Nick is suggesting) is the best option for the moment. It will have to be only available for users willing to build from source themselves.

Side note:
I started to explore a concept where we would have a MARLEY (or other dependency) come in via external python package, but this can't be done purely via dynamic shared object loading at runtime on macOS and the other solutions are not very nice...

2026-05-15 19:45 UTC, austinschneider commented on projects/interactions/private/PythiaDISCrossSection.cxx
That said, we should really consider making Pythia and MARLEY builds part of the CI testing.

2026-05-19 09:15 UTC, MiaochenJin commented on projects/distributions/private/secondary/vertex/SecondaryBoundedVertexDistribution.cxx
You are right. we do not currently have any hadronization logic any more. A new commit will remove all dead code, and we shouldn't need to change the Secondary*Distribution definitions any more.

2026-05-19 09:18 UTC, MiaochenJin commented on projects/injection/private/Injector.cxx
no worries. this is no longer a concern. as commented in another place, we do not have hadronization class now

2026-05-20 11:16 UTC, MiaochenJin commented on projects/dataclasses/public/SIREN/dataclasses/ParticleTypes.def
> +X(CharmBar, -4)
Done — removed `X(Charm, 4)` and `X(CharmBar, -4)`; they were PDG-code duplicates of the `X(c, 4)` / `X(cBar, -4)`
  entries defined above. Also moved `X(K0, 311)` / `X(K0Bar, -311)` next to `X(K0_Short, 310)` in the mesons section. The
   only `Charm`/`CharmBar` callers were `isQuark()` (in `Particle.cxx`) and a switch case in
  `QuarkDISFromSpline::getHadronMass`, both removed as dead code now that QuarkDIS emits D mesons directly rather than
  bare charm quarks. The `c` / `cBar` entries (used by HNL and electroweak decay code via `Constants::charmMass`) stay as
   the canonical charm-quark tag.

2026-05-20 11:17 UTC, MiaochenJin commented on projects/detector/private/DetectorModel.cxx
Done — added `constexpr static double DetectorModel::distance_threshold = 1e-5;` to the header with a short comment,
  and the two `<= 1e-5` checks at `DetectorModel.cxx:713` and `:1023` now use the constant. The bare
  `direction.magnitude() == 0` exact-zero checks elsewhere are left as-is since they're a different condition (exact
  zero, not near-zero).

2026-05-20 12:59 UTC, MiaochenJin commented on projects/dataclasses/private/InteractionRecord.cxx
Done

2026-05-20 12:59 UTC, MiaochenJin commented on cmake/Packages/photospline.cmake
It does not change any splines. It is merely adding back in the missing support for some declared but not compiled functions within photospline

2026-05-20 13:12 UTC, MiaochenJin commented on projects/injection/public/SIREN/injection/Weighter.tcc
This was incorrectly pushed. Reverted now. The QuarkDISFromSpline class correctly handles rate calculation.

2026-05-21 04:39 UTC, austinschneider commented on projects/dataclasses/private/InteractionRecord.cxx
This file's diff is now only whitespace changes, I think we can remove these changes.

2026-05-21 17:36 UTC, nickkamp1 commented on projects/detector/private/DetectorModel.cxx
> +    }
@MiaochenJin can we remove the commented line? If I remember correctly, this error occurs when the particle travels essentially zero distance, so should we just return 0 for the InteractionDepth to be safe as Austin suggested in 2024?

2026-05-21 18:31 UTC, nickkamp1 commented on projects/detector/private/DetectorModel.cxx
see [thread below](https://github.com/Harvard-Neutrino/SIREN/pull/74/changes#r3283169926)

2026-05-21 20:02 UTC, nickkamp1 commented on projects/injection/private/Injector.cxx
I think this is no longer necessary now, as the changes were reverted. @MiaochenJin should confirm then we can resolve this

2026-05-21 21:39 UTC, nickkamp1 requested changes
One small comment in Constants.h, otherwise many comments in SIREN_Controller.py

2026-05-21 21:39 UTC, nickkamp1 commented on projects/utilities/public/SIREN/utilities/Constants.h
> +static const double CharmMass          = 1.27; // GeV (charm-quark mass, meson-context legacy name)
@MiaochenJin can we not just use charmMass below? I don't think we should have both

2026-05-21 21:39 UTC, nickkamp1 commented on python/SIREN_Controller.py
These are pretty extensive changes to SIREN_Controller. Are they all necessary? Inline comments below

2026-05-21 21:39 UTC, nickkamp1 commented on python/SIREN_Controller.py
> +        # Define the primary injection process primary type.
This change was not necessary before, and doesn't exist in the main branch, so I don't understand the comment about upstream PR 71. What has changed in this branch?

2026-05-21 21:39 UTC, nickkamp1 commented on python/SIREN_Controller.py
> -            if fid_vol_secondary and self.fid_vol is not None:
why have we removed the fid_vol_secondary flag? This should be optional for the user

2026-05-21 21:39 UTC, nickkamp1 commented on python/SIREN_Controller.py
> -        # Define the primary physical process primary type
same question here

2026-05-21 21:39 UTC, nickkamp1 commented on python/SIREN_Controller.py
> -            if fid_vol_secondary and self.fid_vol is not None:
same question, why are we removing this flag?

2026-05-21 21:39 UTC, nickkamp1 commented on python/SIREN_Controller.py
> -                _injection.Injector(
where did these underscores come from? I think the pybind11 class is still Injector and not _Injector, and Weighter, not _Weighter

2026-05-21 22:06 UTC, austinschneider commented on python/SIREN_Controller.py
> -                _injection.Injector(
These are monkey patched in the top-level SIREN \_\_init\_\_.py so that the interface is a little bit more convenient on the python side.

https://github.com/Harvard-Neutrino/SIREN/blob/main/python/__init__.py#L33-L45

2026-05-22 19:46 UTC, nickkamp1 submitted a review, later dismissed
all of my comments addressed with latest commit

2026-06-26 21:11 UTC, austinschneider commented on projects/interactions/private/PythiaDISCrossSection.cxx
> +}
This override of `TotalCrossSectionAllFinalStates` bakes in the assumption that the only ONE final state is possible through this cross section which is directly contradicted by the `GetPossibleSignatures` function. The solution is to remove this override.
```suggestion
```

2026-06-26 21:11 UTC, austinschneider commented on projects/interactions/public/SIREN/interactions/PythiaDISCrossSection.h
> +    double TotalCrossSectionAllFinalStates(dataclasses::InteractionRecord const &) const override;
```suggestion
```

2026-06-26 21:15 UTC, austinschneider commented on projects/interactions/private/PythiaDISCrossSection.cxx
> +    }
We should remove this hardcoded path to prevent divergent behavior in scripts across cluster environments.

2026-06-26 21:22 UTC, austinschneider commented on projects/interactions/private/PythiaDISCrossSection.cxx
> +}
Is this missing the FragmentationFraction?

2026-06-26 23:16 UTC, nickkamp1 commented on projects/interactions/private/PythiaDISCrossSection.cxx
> +    }
removing in new commit, agreed

2026-06-26 23:17 UTC, nickkamp1 commented on projects/interactions/private/PythiaDISCrossSection.cxx
> +}
i think it is, good catch

2026-06-29 06:22 UTC, austinschneider approved these changes

2026-06-29 06:22 UTC, merged